name: Functional Tests

on: [pull_request]

jobs:
  tests:
    name: Run functional tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: test
      DB_PASSWORD: test

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ${{env.DB_USER}}
          MYSQL_PASSWORD: ${{env.DB_PASSWORD}}
          MYSQL_DATABASE: ${{env.DB_DATABASE}}
          MYSQL_ROOT_PASSWORD: ${{env.DB_PASSWORD}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: apcu, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run composer install
        run: export NODE_OPTIONS=--openssl-legacy-provider && php bin/console dependencies install

      - name: Load timezone data
        run: |
          MARIADB_CONTAINER=$(docker ps -q --filter "publish=3306")
          docker exec "$MARIADB_CONTAINER" \
            bash -c "mariadb-tzinfo-to-sql /usr/share/zoneinfo | mariadb -uroot -p${DB_PASSWORD} mysql"
          mysql -h 127.0.0.1 -u root -p$DB_PASSWORD \
            -e "GRANT SELECT ON mysql.time_zone_name TO '$DB_USER'@'%'; FLUSH PRIVILEGES;"

      - name: Install ITSM-ng
        run: php bin/console itsmng:database:install --config-dir=${{ github.workspace }}/tests/config -H 127.0.0.1 -u $DB_USER -p $DB_PASSWORD -d $DB_DATABASE -n

      - name: Run functional tests
        run: vendor/bin/atoum -p 'php -d memory_limit=512M' --debug --force-terminal --use-dot-report --bootstrap-file tests/bootstrap.php --fail-if-skipped-methods --no-code-coverage --max-children-number 1 -d tests/functionnal
